services:
  autodump.server:
    image: autodump.server
    build:
      context: .
      dockerfile: AutoDump.Server/Dockerfile
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address ":9001" /data
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set autodump http://minio:9000 adminadmin adminadmin;
      /usr/bin/mc mb autodump/autodump-dumps;
      exit 0;
      "
