services:
  guts.server:
    image: guts.server
    build:
      context: .
      dockerfile: Guts.Server/Dockerfile
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server --console-address ":9001" /data
